# 100 numpy exercises

In [2]:
%run initialise.py     

### 1. Importe o pacote numpy com o nome np (★☆☆)

In [3]:
import numpy as np

### 2. Imprima a versão numpy e a configuração (★☆☆)

In [6]:
np.__version__

'1.26.4'

### 3. Crie um vetor nulo de tamanho 10 (★☆☆)

In [8]:
zeros10 = np.zeros(10)
print(zeros10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Como encontrar o tamanho da memória de qualquer array (★☆☆)

In [11]:
print(zeros10.size) # quantidade de itens no array
print(zeros10.itemsize) # quantidade de bytes de cada item no array
print("%d bytes" % (zeros10.size * zeros10.itemsize))

10
8
80 bytes


### 5. Como obter a documentação da função numpy add da linha de comando? (★☆☆)

In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Crie um vetor nulo de tamanho 10, mas o quinto valor é 1 (★☆☆)

In [15]:
zeros10[4]=1
print(zeros10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
print(v[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
eye3 = np.eye(3)
print(eye3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values (★☆☆)