<a href="https://colab.research.google.com/github/ValesckaBarros/Numpy100/blob/main/numpy100.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

In [ ]:
%run initialise.py

### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.26.4'

### 3. Create a null vector of size 10 (★☆☆)


In [ ]:
zeros10 = np.zeros(10)
print(zeros10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array (★☆☆)


In [ ]:
print(zeros10.size) # quantidade de itens no array
print(zeros10.itemsize) # quantidade de bytes de cada item no array
print("%d bytes" % (zeros10.size * zeros10.itemsize))

10
8
80 bytes


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
zeros10[4]=1
print(zeros10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(v[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [2]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
eye3 = np.eye(3)
print(eye3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values (★☆☆)

In [3]:
m = np.random.random((3,3,3))
print(m)

[[[0.53472526 0.10490639 0.63096328]
  [0.28868852 0.4881786  0.5835212 ]
  [0.33314377 0.60076667 0.28919646]]

 [[0.85766039 0.58208376 0.09413353]
  [0.47136651 0.83120768 0.67577811]
  [0.82291082 0.94666852 0.82258281]]

 [[0.37285593 0.90301456 0.03355378]
  [0.92780278 0.66377095 0.98954508]
  [0.8299914  0.20171469 0.52687011]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [4]:
z = np.random.random((10,10))
print(z.min())
print(z.max())

0.01537892191183865
0.9870407341700926


### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [5]:
z = np.random.random(30)
print(z.mean())

0.500355064746953


### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [6]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [11]:
x = np.zeros((10,10))
x[1:-1,1:-1] = 1
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)

In [ ]:
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [13]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [18]:
b = np.zeros((8,8),dtype=int)
b[1::2,::2] = 1
b[::2,1::2] = 1
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [19]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [20]:
checkerboard = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
